spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/greenHandChen/spring-cloud-demo2.git # git仓库地址
          search-paths:  eureka-config-repo # 存放配置文件的文件夹
  jackson:
      serialization:
        indent-output: true #美化JSON格式数据
server:
  port: 1201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

