spring:
  cloud:
    config:
      server:
        git:
          # 动态刷新需要配置帐号
          username: 214697163@qq.com
          password: qq172513

          uri: https://github.com/greenHandChen/spring-cloud-demo2.git # git仓库地址
          search-paths:  cloud-config-repo # 存放配置文件的文件夹
  rabbitmq:
    username: root
    password: root
    host: 192.168.31.128
    port: 5672
  jackson:
      serialization:
        indent-output: true #美化JSON格式数据
  application:
    name: config-server
server:
  port: 1201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 避免权限问题
management:
  security:
    enabled: false


