spring:
  application:
    name: cloud-stream-producer
  rabbitmq:
    port: 5672
    host: 192.168.31.128
    username: root
    password: root
  cloud:
    stream:
      bindings:
        myOutput: # 输出通道名称
          destination: hello-C # 针对输出通道来说，如果定义了destination,那么交换机以及消息的routing key名称将都为这个名称。
          producer:
            partitionKeyExpression: payload # el表达式的分区KEY
            partitionCount: 2
server:
  port: 2003
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
management:
  security:
    enabled: false