spring:
  application:
    name: cloud-zipkin-server-by-rabbitmq
  rabbitmq:
    username: root
    password: root
    host: 192.168.31.128
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sleuth_zipkin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    schema: classpath:/mysql.sql
    initialize: true
    continue-on-error: true
#  sleuth:
#    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
server:
  port: 9411

# 选择zipkin数据持久化方案
zipkin:
  storage:
    type: mysql